### ISSUE TITLE
Install nginx mainline version on bionic

### ISSUE THREAD

**Issue by acs-ferreira** [ReinerNippes/nextcloud#33]
Actually, only Xenial gets mainline version, not Bionic (it sticks with 1.14.0).
Any reason for this ?

https://github.com/ReinerNippes/nextcloud/blob/master/roles/prep_nginx/tasks/Ubuntu.yml

**Comment by ReinerNippes** [comment]
you may try this:
https://github.com/ReinerNippes/nextcloud/blob/4f473a1868918c18b4e07aadc53f49103098eccc/roles/prep_nginx/tasks/Ubuntu.yml#L12

beware that i changed the postgresql installation from docker based to package base on the branch flex.port. if you used the master branch before just copy the file prep_nginx/tasks/Ubuntu.yml

**Comment by acs-ferreira** [comment]
I'll give it a try ASAP, thanks.

**Comment by ReinerNippes** [comment]
If you prefer the standard nginx repo:

```
---
# Ubuntu related OS tasks

- name: add an apt key by id for nginx repo
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    id: ABF5BD827BD9BF62
    state: present

- name: add additional repos nginx
  apt_repository:
    repo: 'deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx'
    validate_certs: true
    update_cache: true
    state: present

- name: remove standard nginx
  apt:
    name:
      - nginx-full
    state: absent

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true

- name: install additional packages
  apt:
    name: nginx
    autoremove: true
    state: latest

- name: install needed packages
  apt:
    name:
      - python-pip
      - python-netaddr
    state: latest
```
and you should check the ssl config and adjust it to your needs.
https://www.ssllabs.com/ssltest/analyze.html
